"""Modelos Pydantic para o SDK CNPJá."""

from ._enums import (
    AgeRange,
    CacheStrategy,
    CompanySizeId,
    EmailOwnership,
    OfficeLinkType,
    OfficeStatusId,
    PersonType,
    PhoneType,
    RegistrationStatusId,
    RegistrationTypeId,
    State,
    SuframaStatusId,
    SuframaTribute,
)
from .ccc import CccCertificateParams, CccDto, CccReadParams, CccSource, CccState
from .common import (
    ActivityDto,
    AddressDto,
    CompanySizeDto,
    CountryDto,
    EmailDto,
    MemberAgentDto,
    NatureDto,
    OfficeLinkDto,
    OfficeReasonDto,
    OfficeSpecialDto,
    OfficeStatusDto,
    OfficeSuframaDto,
    PersonBaseDto,
    PhoneDto,
    RegistrationDto,
    RegistrationStatusDto,
    RegistrationTypeDto,
    RoleDto,
    SimplesSimeiDto,
    SimplesSimeiHistoryDto,
    SuframaActivityDto,
    SuframaIncentiveDto,
    SuframaStatusDto,
)
from .company import CompanyDto, CompanyOfficeDto
from .credit import CreditDto
from .list import (
    ListCreateParams,
    ListDto,
    ListExportCreateParams,
    ListExportDto,
    ListExportIdDto,
    ListExportPageDto,
    ListExportSearchParams,
    ListJobOptionsDto,
    ListLinkDto,
    ListPageDto,
    ListQueryDto,
    ListSearchParams,
    ListSummaryDto,
    ListUpdateParams,
)
from .office import (
    MemberDto,
    OfficeCompanyDto,
    OfficeDto,
    OfficeMapParams,
    OfficePageDto,
    OfficePageRecordDto,
    OfficeReadParams,
    OfficeSearchParams,
    OfficeStreetParams,
)
from .person import (
    PersonDto,
    PersonMemberCompanyDto,
    PersonMemberDto,
    PersonPageDto,
    PersonSearchParams,
)
from .rfb import RfbCertificateParams, RfbDto, RfbMemberDto, RfbReadParams
from .simples import SimplesCertificateParams, SimplesDto, SimplesReadParams
from .suframa import SuframaCertificateParams, SuframaDto, SuframaReadParams
from .zip import ZipDto

__all__ = [
    # Enums
    "AgeRange",
    "CacheStrategy",
    "CompanySizeId",
    "EmailOwnership",
    "OfficeLinkType",
    "OfficeStatusId",
    "PersonType",
    "PhoneType",
    "RegistrationStatusId",
    "RegistrationTypeId",
    "State",
    "SuframaStatusId",
    "SuframaTribute",
    # Common
    "ActivityDto",
    "AddressDto",
    "CompanySizeDto",
    "CountryDto",
    "EmailDto",
    "MemberAgentDto",
    "NatureDto",
    "OfficeLinkDto",
    "OfficeReasonDto",
    "OfficeSpecialDto",
    "OfficeStatusDto",
    "OfficeSuframaDto",
    "PersonBaseDto",
    "PhoneDto",
    "RegistrationDto",
    "RegistrationStatusDto",
    "RegistrationTypeDto",
    "RoleDto",
    "SimplesSimeiDto",
    "SimplesSimeiHistoryDto",
    "SuframaActivityDto",
    "SuframaIncentiveDto",
    "SuframaStatusDto",
    # Office
    "MemberDto",
    "OfficeCompanyDto",
    "OfficeDto",
    "OfficeMapParams",
    "OfficePageDto",
    "OfficePageRecordDto",
    "OfficeReadParams",
    "OfficeSearchParams",
    "OfficeStreetParams",
    # Company
    "CompanyDto",
    "CompanyOfficeDto",
    # Person
    "PersonDto",
    "PersonMemberCompanyDto",
    "PersonMemberDto",
    "PersonPageDto",
    "PersonSearchParams",
    # RFB
    "RfbCertificateParams",
    "RfbDto",
    "RfbMemberDto",
    "RfbReadParams",
    # Simples
    "SimplesDto",
    "SimplesReadParams",
    "SimplesCertificateParams",
    # CCC
    "CccCertificateParams",
    "CccDto",
    "CccReadParams",
    "CccSource",
    "CccState",
    # SUFRAMA
    "SuframaCertificateParams",
    "SuframaDto",
    "SuframaReadParams",
    # ZIP
    "ZipDto",
    # Credit
    "CreditDto",
    # List
    "ListCreateParams",
    "ListDto",
    "ListExportCreateParams",
    "ListExportDto",
    "ListExportIdDto",
    "ListExportPageDto",
    "ListExportSearchParams",
    "ListJobOptionsDto",
    "ListLinkDto",
    "ListPageDto",
    "ListQueryDto",
    "ListSearchParams",
    "ListSummaryDto",
    "ListUpdateParams",
]
